config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#root'

  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: {format: :json} do
    resources :todos
  end

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :username, presence: true
  validates :password_digest, presence: {message: "Password can't be blank"}
  validates :password, length: { minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  has_many :todos

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    if user
      if user.is_password?(password)
        return user
      else
        User.errors.full_messages = "Invalid Username or Password"
      end
    end
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
    self.save
  end

end

app/controllers/api/todos_controller.rb
class Api::TodosController < ApplicationController

  def new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user_id = current_user.id
    if @todo.save
      render :show
    else
      render json: @todo.errors.full_messages
    end
  end

  def index
    @todos = current_user.todos
    render :index
  end

  def show
    @todo = Todo.find(params[:id])
    render :show
  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.update(todo_params)
      render :show
    else
      render json: @todo.errors.full_messages
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    if @todo.destroy
      render :show
    else
      render json: @todo.errors.full_messages
    end
  end

  def edit
  end

  private

  def todo_params
    params.require(:todo).permit(:name, :pomodoros)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    session[:session_token] = user.reset_session_token!
  end

  def sign_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  private

  def check_signed_in
    if !signed_in?
      redirect_to new_session_url
    end
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    username = params[:user][:username].downcase
    if username["@geemailer.com"].nil?
      username += "@geemailer.com"
    end

    @user = User.find_by_credentials(username, params[:user][:password])
    if @user
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid username/password"]
      render :new
    end
  end

  def destroy
    sign_out
    render :new
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    username = params[:user][:username].downcase
    @user = User.find_by_credentials(username, params[:user][:password])
    if @user
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid username/password"]
      render :new
    end
  end

  def destroy
    sign_out
    render :new
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_action :check_signed_in

  def root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

  end


  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
    <%= error %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>Pomodoro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/session/new.html.erb
<h1 class="sign-header">Sign in to continue to your To-Do List</h1>
<div class="enter_form">
<figure id="avatar" class="smaller"></figure>
<br>
<form action="<%= session_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"></input>
  <input class="sign_in_input" type="text" value="" name="user[username]" placeholder="Username or Email"></input><br>
  <input class="sign_in_input" type="password" value="" name="user[password]" placeholder="Password"></input><br>
  <h3 class="errors"><%= render partial: "layouts/errors"%><h3>
  <p>
  </p>
  <button class="log_button" type="submit" value="Sign In">Sign In</button>
</form>

<form action="<%= session_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"></input>
  <input type="hidden" type="text" value="hipster01" name="user[username]"></input><br>
  <input type="hidden" value="duuuude" name="user[password]"></input><br>
  <p>
  </p>
  <button class="log_button" value="Sign In as a Hipster!">Sing In as a Hipster! (Guest)</button>
</form>
<p>
</p>

</div>

<%=link_to "Create account", new_user_url %>

app/views/static_pages/root.html.erb
<div id="pomodoro">
</div>

app/views/users/new.html.erb
<h1 id="sign-header">Please Sign Up</h1>

<div id="enter-form">
<figure id="avatar" class="smaller"></figure>
<br>
<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"></input>
  <input id="sign-in-input" type="text" value="" name="user[username]" placeholder="Username"></input><br>
  <input id="sign-in-input" type="password" value="" name="user[password]" placeholder="Password"></input><br>
  <h3 class="errors"><%= render partial: "layouts/errors"%><h3>
  <p>
  </p>
  <button id="log-button" type="submit" value="Sign In">Sign Up</button>
</form>
<p>
</p>

</div>

<%=link_to "Sign In", new_session_url %>